export const ActionTypes = {
  FETCH_MEALS_SUCCESS: 'FETCH_MEALS_SUCCESS',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  ADD_NEW_MEAL: 'ADD_NEW_MEAL',
  TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
};